# Generated by Django 6.0.2 on 2026-02-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, help_text='The cultural term or phrase (case-insensitive lookup).', max_length=200, unique=True)),
                ('definition', models.TextField(help_text='Cultural definition and context for this term.')),
                ('image_url', models.URLField(blank=True, default='', help_text='Optional image URL illustrating the term.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cultural Term',
                'verbose_name_plural': 'Cultural Terms',
                'ordering': ['term'],
            },
        ),
    ]
