# Generated by Django 6.0.2 on 2026-02-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalterm',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Category (food, culture, expression, etc.).', max_length=50),
        ),
        migrations.AddField(
            model_name='culturalterm',
            name='language',
            field=models.CharField(blank=True, default='', help_text='Language of origin (e.g. Chavacano, Tausug).', max_length=50),
        ),
        migrations.CreateModel(
            name='TranslationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_lang', models.CharField(max_length=10)),
                ('target_lang', models.CharField(max_length=10)),
                ('mode', models.CharField(choices=[('formal', 'Formal'), ('street', 'Street')], max_length=10)),
                ('input_text', models.TextField()),
                ('input_chars', models.PositiveIntegerField()),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_text', models.TextField(blank=True, default='')),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(max_length=100)),
                ('pivot_used', models.BooleanField(default=False)),
                ('latency_ms', models.FloatField(help_text='Total inference time in milliseconds.')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('wiki_voz_triggered', models.BooleanField(default=False)),
                ('wiki_voz_term', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Translation Log',
                'verbose_name_plural': 'Translation Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_api_tr_created_485ac0_idx'), models.Index(fields=['source_lang', 'target_lang'], name='core_api_tr_source__b46bf9_idx'), models.Index(fields=['status'], name='core_api_tr_status_a78b15_idx')],
            },
        ),
    ]
