# Generated by Django 6.0.2 on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_culturalterm_category_culturalterm_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalterm',
            name='language',
            field=models.CharField(
                blank=True,
                choices=[
                    ('en', 'English'),
                    ('es', 'Spanish'),
                    ('tl', 'Tagalog'),
                    ('cbk', 'Chavacano (Zamboanga)'),
                    ('hil', 'Hiligaynon'),
                    ('ceb', 'Cebuano/Bisaya'),
                ],
                default='',
                help_text='Language of origin (e.g. Chavacano, Tausug).',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='translationlog',
            name='source_lang',
            field=models.CharField(
                choices=[
                    ('auto', 'Auto-Detect'),
                    ('en', 'English'),
                    ('es', 'Spanish'),
                    ('tl', 'Tagalog'),
                    ('cbk', 'Chavacano (Zamboanga)'),
                    ('hil', 'Hiligaynon'),
                    ('ceb', 'Cebuano/Bisaya'),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='translationlog',
            name='target_lang',
            field=models.CharField(
                choices=[
                    ('en', 'English'),
                    ('es', 'Spanish'),
                    ('tl', 'Tagalog'),
                    ('cbk', 'Chavacano (Zamboanga)'),
                    ('hil', 'Hiligaynon'),
                    ('ceb', 'Cebuano/Bisaya'),
                ],
                max_length=10,
            ),
        ),
    ]
