# Generated by Django 6.0.2 on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_add_es_language_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalterm',
            name='language',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Language of origin (e.g. Chavacano, Tausug).',
                max_length=50,
            ),
        ),
    ]
