# Generated by Django 6.0.2 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_culturalterm_language_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationlog',
            name='route_confidence',
            field=models.FloatField(
                blank=True,
                default=None,
                help_text='Confidence score from the direct route prior to any fallback.',
                null=True,
            ),
        ),
    ]
