# Generated by Django 6.0.4 on 2026-04-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0005_translationlog_route_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturalterm',
            name='trigger_words',
            field=models.JSONField(blank=True, default=list, help_text='List of trigger terms/phrases used for Wiki-Voz interception.'),
        ),
        migrations.AlterField(
            model_name='translationlog',
            name='route_confidence',
            field=models.FloatField(blank=True, default=None, help_text='Mean token-level confidence from direct inference pass (0-1).', null=True),
        ),
    ]
