# Generated by Django 6.0.4 on 2026-04-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_culturalterm_trigger_words_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturalterm',
            name='term',
            field=models.CharField(db_index=True, help_text='The cultural term or phrase (case-insensitive lookup).', max_length=200),
        ),
        migrations.AddConstraint(
            model_name='culturalterm',
            constraint=models.UniqueConstraint(fields=('term', 'language'), name='unique_cultural_term_per_language'),
        ),
    ]
